import test from "node:test";
import assert from "node:assert/strict";
import { onRequest } from "../_middleware.js";

test("correlation IDs are generated by the server and successful responses are not logged", async (t) => {
  const log = t.mock.method(console, "error", () => {});
  const request = new Request(
    "https://app.example/api/google/session?token=private",
    { headers: { "X-StreamLion-Request-ID": "untrusted" } },
  );
  const response = await onRequest({
    request,
    next: async () =>
      new Response("ok", {
        headers: {
          "Cache-Control": "no-store",
          "Set-Cookie": "safe-cookie",
          Location: "/",
        },
      }),
  });
  assert.match(
    response.headers.get("X-StreamLion-Request-ID"),
    /^[a-f0-9-]{36}$/,
  );
  assert.equal(response.headers.get("Set-Cookie"), "safe-cookie");
  assert.equal(await response.text(), "ok");
  assert.equal(log.mock.callCount(), 0);
});
test("uncaught failures return a safe response and bounded fields without private diagnostic data", async (t) => {
  const entries = [];
  t.mock.method(console, "error", (entry) => entries.push(JSON.parse(entry)));
  const request = new Request(
    "https://app.example/api/purchase/private-account?token=secret",
    { headers: { Cookie: "private-cookie" } },
  );
  const response = await onRequest({
    request,
    next: async () => {
      throw new Error("provider-secret private-account private-cookie");
    },
  });
  assert.equal(response.status, 503);
  assert.equal(response.headers.get("Cache-Control"), "no-store");
  const body = await response.json();
  assert.equal(body.requestId, response.headers.get("X-StreamLion-Request-ID"));
  assert.equal(entries[0].requestId, body.requestId);
  assert.equal(entries[0].route, "purchase");
  assert.ok(!/secret|cookie|account/.test(JSON.stringify({ body, entries })));
});
test("handled service failures also receive correlation IDs without changing their body", async (t) => {
  const entries = [];
  t.mock.method(console, "error", (entry) => entries.push(JSON.parse(entry)));
  const response = await onRequest({
    request: new Request("https://app.example/api/health"),
    next: async () => new Response('{"status":"degraded"}', { status: 503 }),
  });
  assert.equal(await response.text(), '{"status":"degraded"}');
  assert.equal(entries[0].route, "health");
  assert.equal(entries[0].status, 503);
});
test("failure logging has an isolate-local ceiling and recovers in the next window", async (t) => {
  const entries = [];
  t.mock.method(console, "error", (entry) => entries.push(entry));
  let now = Date.now() + 60001;
  t.mock.method(Date, "now", () => now);
  const invoke = () =>
    onRequest({
      request: new Request("https://app.example/api/health"),
      next: async () => new Response("Unavailable", { status: 503 }),
    });
  await Promise.all(Array.from({ length: 100 }, invoke));
  assert.equal(entries.length, 60);
  now += 60001;
  await invoke();
  assert.equal(entries.length, 61);
});
